# Generated by Django 5.2.9 on 2025-12-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='city',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='other_interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
