# Generated by Django 5.2.9 on 2025-12-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userpreferences_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
