# Generated by Django 5.2.9 on 2025-12-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='noise_tolerance',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_file',
            field=models.ImageField(default='default.jpg', upload_to='room_photos/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserVerification',
        ),
    ]
