# Generated by Django 5.2.9 on 2025-12-28 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_listingimage_image_url_remove_user_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('verification_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_image', models.ImageField(upload_to='verification_docs/')),
                ('document_type', models.CharField(default='national_id', max_length=50)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_verifications',
            },
        ),
    ]
