# Generated by Django 5.2.9 on 2026-01-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlisting',
            name='room_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('hostel', 'Hostel'), ('private', 'Private'), ('shared', 'Shared'), ('bedsitter', 'Bedsitter')], max_length=20),
        ),
    ]
