# Generated by Django 5.2.9 on 2026-01-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='noise_tolerance',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
