# Generated by Django 6.0 on 2026-02-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userpreferences_noise_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='is_actively_looking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='target_city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
