import os


"""
Django settings for roommate_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lbk$t!3iwmgzc6gzsy#o!z9+v!3yoz!1+(2zjk-$ean@at-zp('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    ".ngrok-free.app",
    ".ngrok-free.dev",
]
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app', # Wildcard for any ngrok address
    'https://*.ngrok-free.dev', # <--- Add this line
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]



# Application definition
INSTALLED_APPS = [
    'jazzmin',                  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party
    'rest_framework',
    'drf_spectacular',
    
    # Local apps
    'core',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'roommate_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'roommate_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'roommate_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'db'), # 'db' matches the service name in docker-compose
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# TELL DJANGO TO USE YOUR CUSTOM USER MODEL
AUTH_USER_MODEL = 'core.User'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', # Add this line
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Optional: JWT Settings (Customize token lifetime)
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), # Keep user logged in for 1 day
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'USER_ID_FIELD': 'user_id',
}

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Find a Roommate API',
    'DESCRIPTION': 'API documentation for the roommate matching system',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # This ensures the "Authorize" button works with your JWT Token
    'COMPONENT_SPLIT_REQUEST': True,
}
JAZZMIN_SETTINGS = {
    # Branding
    "site_title": "Roommate Admin",
    "site_header": "Roommate Finder",
    "site_brand": "Roommate Admin",
    "welcome_sign": "Welcome to the Admin Dashboard",
    "copyright": "CUEA Final Year Project",
    "search_model": "core.User",

    # UI Customization
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "API Docs", "url": "/api/docs/", "new_window": True}, # Link to Swagger
    ],
    
    # Sidebar Icons (FontAwesome)
    "icons": {
        "core.User": "fas fa-users",
        "core.RoomListing": "fas fa-home",
        "core.Match": "fas fa-heart",
        "core.Payment": "fas fa-money-bill-wave",
        "core.Conversation": "fas fa-comments",
        "core.Review": "fas fa-star",
    },
    
    # Order of apps in sidebar
    "order_with_respect_to": ["core", "auth"],
}

# Optional: Tweak the colors (UI Tweaks)
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",   # Options: darker, slate, solar, superhero
    "dark_mode_theme": "darkly",
}